deploy:
  registry: registry.hub.docker.com
  os: linux
  arch: amd64
  no_build: false
  server:
    repository: "nathanbrophy/example-server"
    tag: "v1.0.0"
  controller:
    repository: "nathanbrophy/example-controller"
    tag: "v1.0.0"
  terraform: 
    cluster_name: "exampleCluster2"
    region: "us-west-1"
