apiVersion: acme.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s
  name: {{ .Values.cr.name }}
  namespace: {{ .Values.cr.namespace.name }}
spec:
  application:
    image: {{ .Values.cr.image }}
    port: 8081
