apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "operator-controller.labels" . | nindent 4 }}
  name: k8s-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-leader-election-role
subjects:
- kind: ServiceAccount
  name: k8s-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "operator-controller.labels" . | nindent 4 }}
  name: k8s-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-manager-role
subjects:
- kind: ServiceAccount
  name: k8s-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "operator-controller.labels" . | nindent 4 }}
  name: k8s-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-proxy-role
subjects:
- kind: ServiceAccount
  name: k8s-controller-manager
  namespace: {{ .Release.Namespace }}