apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "operator-controller.labels" . | nindent 4 }}
  name: k8s-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager