name: 'Continuous Delivery Pipeline'

on:
    push:
        branches: [ "main" ]
    workflow_dispatch: 
  
jobs:
    infrastructure-apply:
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: ${{ vars.REGION }}
            cluster_name: ${{ vars.CLUSTER_NAME }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: terraform init
          run: |
            cd ./infrastructure/aws 
            terraform init
        - name: terraform apply
          run: |
            cd ./infrastructure/aws 
            terraform apply -var region="${region}" -var cluster_name="${cluster_name}" -auto-approve 
    build_and_push_controller:
        runs-on: ubuntu-latest
        env:
            DOCKER_ID: ${{ secrets.DOCKER_ID }}
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        steps:
        - uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_ID }}
            password: ${{ secrets.DOCKER_PASS }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: "nathanbrophy/example-controller:${{ github.sha }}"
            context: "./k8s"
            file: "./k8s/Dockerfile"
    build_and_push_server:
        runs-on: ubuntu-latest
        env:
            DOCKER_ID: ${{ secrets.DOCKER_ID }}
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }} 
        steps:
        - uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_ID }}
            password: ${{ secrets.DOCKER_PASS }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: "nathanbrophy/example-server:${{ github.sha }}"
            context: "./server"
            file: "./server/Dockerfile"
    deploy_application_to_env:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: ${{ vars.REGION }}
            cluster_name: ${{ vars.CLUSTER_NAME }}
        needs: 
        - infrastructure-apply
        - build_and_push_controller
        - build_and_push_server
        steps:
            - uses: actions/checkout@v3
            - name: Log into AWS Cluster
              run: |
                aws eks --region "${region}" update-kubeconfig --name "${cluster_name}"
            - name: Helm Install
              run: |
                helm upgrade pocsample operator-controller \
                    -i \
                    --namespace acme-controller-manager \
                    --create-namespace \
                    -f operator-controller/values.yaml
                    --set cr.image="registry.hub.docker.com/nathanbrophy/example-server:${{ github.sha }}" \
                    --set cr.image="registry.hub.docker.com/nathanbrophy/example-controller:${{ github.sha }}"
        
