name: Docker controller compilation test

# This is here to only test compilation on builds.

on:
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            # IMG is hard coded at the moment, in the future we should
            # use git API to dynamically get the latest tag ref to auto tag the
            # image.
            IMG: "registry.hub.docker.com/nathanbrophy/example-controller:v1.0.0"
        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: |
            cd k8s 
            docker build -f Dockerfile -t ${IMG} . 
