name: Docker build and push controller

on:
  push: 
    branches: [ "main" ]

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        env:
            DOCKER_ID: ${{ secrets.DOCKER_ID }}
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        steps:
        - uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_ID }}
            password: ${{ secrets.DOCKER_PASS }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: "registry.hub.docker.com/nathanbrophy/example-controller:v1.0.0"
            context: "./k8s"
            file: "./k8s/Dockerfile"
