name: Docker build and push images

on:
  push: 
    branches: [ "main" ]

jobs:
    build_and_push_controller:
        runs-on: ubuntu-latest
        env:
            DOCKER_ID: ${{ secrets.DOCKER_ID }}
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        steps:
        - uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_ID }}
            password: ${{ secrets.DOCKER_PASS }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: "registry.hub.docker.com/nathanbrophy/example-controller:v1.0.0"
            context: "./k8s"
            file: "./k8s/Dockerfile"
    build_and_push_server:
              runs-on: ubuntu-latest
              env:
                  DOCKER_ID: ${{ secrets.DOCKER_ID }}
                  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
              steps:
              - uses: actions/checkout@v3
              - name: Set up QEMU
                uses: docker/setup-qemu-action@v2
              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
              - name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKER_ID }}
                  password: ${{ secrets.DOCKER_PASS }}
              - name: Build and push
                uses: docker/build-push-action@v4
                with:
                  push: true
                  tags: "registry.hub.docker.com/nathanbrophy/example-server:v1.0.0"
                  context: "./server"
                  file: "./server/Dockerfile"