name: 'Demo CI CD'
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - develop
    - feature*
permissions:
  contents: read
  pull-requests: read
jobs:
- name: 'lint terraform'
  run: |
    ./infrastructure/aws/lint
