name: 'Demo CI CD'
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - develop
    - feature*
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: 'lint terraform'
      run: |
        pwd
        ls
        ./infrastructure/aws/lint
