name: Example CI CD Pipeline

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: run v2
      run: |
        cd /infrastructure/aws 
        ./lint

