name: Example CI CD Pipeline

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  infrastructure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: terraform init
      run: |
        cd ./infrastructure/aws 
        ./lint

    - name: terraform lint
      run: |
        cd ./infrastructure/aws 
        ./lint

