name: Makefile CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: run v2
      run: ./infrastructure/aws/lint

    - name: Run terraform lint
      run: make tf-lint

