name: Example CI CD Pipeline

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  infrastructure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd ./infrastructure/aws 
        terraform init

    - name: terraform lint
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd ./infrastructure/aws 
        ./lint
    
    - name: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ variables.REGION }}
        cluster_name: ${{ variables.CLUSTER_NAME }}
      run: |
        cd ./infrastructure/aws 
        terraform plan -no-color -var region="${region}" -var cluster_name="${cluster_name}"

