name: Docker server compilation test

# This is here to only test compilation on builds.

on:
    push:
    pull_request:
      branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            # Version is hard coded at the moment, in the future we should
            # use git API to dynamically get the latest tag ref to auto tag the
            # image.
            version: "v1.0.0"
        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: |
            cd server 
            docker login -u ${DOCKER_ID} -p ${DOCKER_PASS}
            make docker-build VERSION=${version}
