name: Infrastructure Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  infrastructure-apply:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: terraform apply
      run: |
        cd ./infrastructure/aws 
        terraform init
        terraform apply -var region="${region}" -var cluster_name="${cluster_name}" -auto-approve 
  

