name: Infrastructure Pipeline

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  infrastructure-plan:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: terraform init
      run: |
        cd ./infrastructure/aws 
        terraform init

    - name: terraform lint
      run: |
        cd ./infrastructure/aws 
        ./lint
    
    - name: terraform plan
      env:
        region: "us-west-1"
        cluster_name: "exampleClusterDevNathan2023"
      run: |
        cd ./infrastructure/aws 
        terraform plan -no-color -var region="${region}" -var cluster_name="${cluster_name}"
  

